### ISSUE TITLE
SimpleMode: a dedent rule with no matching indent throws — a leading `}` crashes rustLegacy/nsis parsing

### ISSUE THREAD

**Issue by monkopedia-reviewer** [Monkopedia/kodemirror#262]
Found while reviewing #261 (the `SequencedCollection` fix). **Pre-existing, not caused by #261**, and
deliberately left out of that PR's scope.

## The bug

`SimpleMode`'s `dedent` rule pops `state.indent` with no emptiness guard:

```kotlin
// legacy-modes/src/commonMain/kotlin/.../SimpleMode.kt:125
if (rule.dedent) {
    state.indent?.let { it.removeAt(it.lastIndex) }
}
```

`startState` seeds `indent = mutableListOf()` whenever any rule sets `indent` or `dedent`, so a
*closing* token that arrives before any *opening* one pops an empty list and throws.

That is reachable in ordinary editing, in shipped modes. `RustLegacy` puts the dedent rule directly
in its `start` state:

```kotlin
SimpleModeRule(Regex("""[\{\[\(]"""), token = null, indent = true),
SimpleModeRule(Regex("""[\}\]\)]"""), token = null, dedent = true)
```

so a Rust document that *begins* with `}` — typing a stray brace into an empty buffer, or scrolling a
viewport onto a fragment — crashes the parse. `Nsis` has nine `dedent = true` rules and the same
exposure.

## Measured

Scratch probe through the public path (`StreamLanguage.define(rustLegacy)` → `EditorState.create` →
`syntaxTree`) with document `"}"`, run as `:legacy-modes:jvmTest`:

```
main @ 30ba3662 (before #261)  ->  NoSuchElementException: null
PR   @ 5d39e7ea (after #261)   ->  IndexOutOfBoundsException: Index -1 out of bounds for length 0
```

Both are uncaught. Nothing in the repo catches either type — `:language` has no `try`/`catch` at all,
so it propagates into composition. On Android below API 35 the same input threw `NoSuchMethodError`
first, which is what #258 was about; with that fixed, this one becomes the visible failure.

**#261 changed only the exception type here, not whether it throws**, which is why it is filed
separately rather than folded in.

## Upstream comparison

CodeMirror 5's `simple-mode` does:

```js
if (rule.indent) state.indent.push(stream.indentation() + cm.getOption("indentUnit"))
if (rule.dedent) state.indent.pop()
```

`[].pop()` returns `undefined` silently. The Kotlin port turned a no-op into a throw. The likely fix
is `removeLastOrNull()` (already used elsewhere in `legacy-modes`, compiles to the static
`CollectionsKt.removeLastOrNull`, and has no `SequencedCollection` counterpart, so it is safe on
API 24+), plus a regression test for a leading `}` in `rustLegacy`.

## Worth checking at the same time

Whether other ports of `Array.prototype.pop()`/`shift()` in `legacy-modes` made the same
no-op-becomes-throw substitution — this is a translation-pattern bug, and there is no reason to
expect it to be the only instance.
